### ISSUE TITLE
Heading "size" is misleading

### ISSUE THREAD

**Issue by aimeos** [olivmonnier/grapesjs-plugin-header#14]
Headings are a structural HTML element and don't be related to any size of the characters (even if browsers display headings of h1 bigger than h2 headings). My suggestion would be to use a label "Heading" instead of "Size" and option labels of "H1", "H2", etc. so editors don't use e.g. H3 heading on top because they want a smallerheading (in terms of font-size) .

**Comment by olivmonnier** [comment]
You can change the value by default with `labelTrait` option.
